### PR TITLE
fix #9 Podcast refresh notification

### LINKED ISSUE #9: Podcast refresh notification should only be displayed when there are new episodes
I shouldn't get a notification every day saying that PodListen looked for new episodes and didn't find any.

### PR DESCRIPTION
**Pull request by Serienfehler**
Added option to show notification only if a new episode has been found.
Added this as a preference, because users who love this app for years still might prefer to get a notification even without retrieving a new episode, so they feel relaxed realizing the app really does its job by searching.  For all other users the new option can easily be switched on.
As I had to touch the several strings.xml for the new preference anyway, I have updated some issues of the german translation.

### CODE REVIEW

**Comment by shanemd** [comment]
Hi @Serienfehler. Apologies for letting this sit for so long. I haven't had to time to test it. I assume you've tested it on your device? Can you post information about any testing you've done? I'm inclined to just merge this so others can benefit.

**Comment by Serienfehler** [comment]
Hi @shanemd, sorry for the late response.
Yes, I have tested it on my device (by just using this version).
It is an approvement for those who want to reduce the number of notifications and doesn't do any harm for those users, who don't need the new option.
But it is not perfect yet: yes, If the user selects to use the new option, and there is no more item in the tab "new episodes" after the next retrieval, it does not display a new notification anymore. Fine. But: It would still pop up a new notification if the next retrieval wouldn't find any new item, but the tab "new episodes" still contains items (from the one of the last retrievals). This is because the code looks to this counter to determine whether a notification needs to be created or not.
An enhanced solution would require to store the number of items from "new episoses" after each retrieval, and only if this number increases, it would need to show a new notification.
I have already started to implement a solution for that, but with some ambiguous results. So that version is not mature enough.
You can merge what we already have, because a new solution wouldn't revert anything of that, but would further enhance it.

**Comment by shanemd** [comment]
Sounds good. I'm going to go ahead and merge this then. I agree that the notification ideally only shows up when new episodes are fetched, but this is still a big improvement.

Can you file another issue for that next improvement so we can track it?

**Comment by Serienfehler** [comment]
Thanks.
I have added issue #29.

**Pull request merged**
